initial_categories = [
    {
        "id": 1,
        "expenseType": "expense",
        "budgetType": "needs",
        "value": "groceries",
        "caption": "Groceries",
        "color": "#0de2a3",
    },
    {
        "id": 2,
        "expenseType": "expense",
        "budgetType": "wants",
        "value": "shopping",
        "caption": "Shopping",
        "color": "#75effd",
    },
    {
        "id": 3,
        "expenseType": "expense",
        "budgetType": "wants",
        "value": "restaurants",
        "caption": "Restaurants",
        "color": "#c4db8e",
    },
    {
        "id": 4,
        "expenseType": "expense",
        "budgetType": "needs",
        "value": "transport",
        "caption": "Transport",
        "color": "#244c55",
    },
    {
        "id": 5,
        "expenseType": "expense",
        "budgetType": "wants",
        "value": "travel",
        "caption": "Travel",
        "color": "#b8fcfa",
    },
    {
        "id": 6,
        "expenseType": "expense",
        "budgetType": "wants",
        "value": "entertainment",
        "caption": "Entertainment",
        "color": "#f3edbe",
    },
    {
        "id": 7,
        "expenseType": "expense",
        "budgetType": "needs",
        "value": "utilities",
        "caption": "Utilities",
        "color": "#ce297a",
    },
    {
        "id": 8,
        "expenseType": "expense",
        "budgetType": "needs",
        "value": "health",
        "caption": "Health",
        "color": "#675679",
    },
    {
        "id": 9,
        "expenseType": "expense",
        "budgetType": "needs",
        "value": "services",
        "caption": "Services",
        "color": "#49c4eb",
    },
    {
        "id": 10,
        "expenseType": "expense",
        "budgetType": "needs",
        "value": "transfers",
        "caption": "Transfers",
        "color": "#07efc2",
    },
    {
        "id": 11,
        "expenseType": "expense",
        "budgetType": "needs",
        "value": "cash",
        "caption": "Cash",
        "color": "#8f82f3",
    },
    {
        "id": 12,
        "expenseType": "expense",
        "budgetType": "wants",
        "value": "general",
        "caption": "General",
        "color": "#4dd694",
    },
    {
        "id": 13,
        "expenseType": "expense",
        "budgetType": "needs",
        "value": "insurance",
        "caption": "Insurance",
        "color": "#efb1385",
    },
    {
        "id": 14,
        "expenseType": "income",
        "budgetType": "savings",
        "value": "salary",
        "caption": "Salary",
        "color": "#173982",
    },
    {
        "id": 15,
        "expenseType": "income",
        "budgetType": "savings",
        "value": "salary",
        "caption": "Salary",
        "color": "#5c7463",
    },
    {
        "id": 16,
        "expenseType": "income",
        "budgetType": "savings",
        "value": "business",
        "caption": "Business",
        "color": "#fd9a7b",
    },
    {
        "id": 17,
        "expenseType": "income",
        "budgetType": "savings",
        "value": "gifts",
        "caption": "Gifts",
        "color": "#cf6888",
    },
    {
        "id": 18,
        "expenseType": "income",
        "budgetType": "savings",
        "value": "extraincome",
        "caption": "Extra Income",
        "color": "#badc95",
    },
    {
        "id": 19,
        "expenseType": "income",
        "budgetType": "savings",
        "value": "other",
        "caption": "Other",
        "color": "#44444b",
    },
]
